# This GitHub action runs your tests for each commit push and/or PR.
name: PRBuilder
on:
  pull_request:

jobs:
  # ensure the code builds...
  build:
    name: Build
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v4.1.1
      - uses: actions/setup-go@v4.1.0
        with:
          go-version: '1.23'
      - name: go mod
        run: |
          go mod tidy
          git diff --exit-code -- go.mod go.sum || \
            (echo; echo "Unexpected difference in go.mod/go.sum files. Run 'go mod tidy' command or revert any go.mod/go.sum changes and commit."; exit 1)
      - name: go fmt
        run: |
          go fmt
          git diff --exit-code || \
            (echo; echo "Unexpected difference. Run 'go fmt' command and commit."; exit 1)
      - name: go generate
        run: |
          go generate
          git diff --exit-code -- docs/ || \
            (echo; echo "Unexpected difference in docs. Run 'go generate' command and commit."; exit 1)
      - name: Build
        run: go build -v ./...
      - name: Test
        run: go test

  lint:
    name: Go Linter
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.1
      - uses: actions/setup-go@v4.1.0
        with:
          go-version: '1.23'
          cache: false
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.54
          args: --timeout=10m --max-issues-per-linter 0 --max-same-issues 0

  tfproviderlint:
    name: Terraform Provider Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.1
      - uses: actions/setup-go@v4.1.0
        with:
          go-version: '1.23'
          cache: false
      - name: install
        run: go install github.com/bflad/tfproviderlint/cmd/tfproviderlintx@v0.30.0
      - name: tfproviderlintx
        run: tfproviderlintx ./...
